version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      build: docker-files/keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      command: -b 0.0.0.0 -Dkeycloak.migration.action=import, \
                -Dkeycloak.migration.provider=singleFile, \
                -Dkeycloak.migration.strategy=OVERWRITE_EXISTING \
                -Dkeycloak.migration.file="/setup/import.json"
      ports:
        - "8080:8080"
      depends_on:
        - postgres